var DB3 = {
    "beers": [
{
    "nr": "1107701",
    "articleid": "734827",
    "articletype": "11077",
    "name": "Samuel Adams Utopias",
    "name2": "",
    "priceinclvat": "1150.00",
    "volumeml": null,
    "priceperlitre": null,
    "introduced": "2013-04-02",
    "finaldelivery": " ",
    "catgegory": "\u00c3\u2013l, Ale",
    "packaging": "Flaska",
    "captype": "",
    "countryoforigin": "",
    "countryoforiginlandname": "USA",
    "producer": "Boston Beer Company",
    "provider": "Galatea Spirits AB",
    "productionyear": "2012",
    "testedproductionyear": "",
    "alcoholstrength": "27%",
    "module": "T7",
    "assortment": "TSE",
    "organic": "0",
    "kosher": "0"
},{
    "nr": "1144703",
    "articleid": "51064",
    "articletype": "11447",
    "name": "Innis & Gunn",
    "name2": "Oak Aged Beer",
    "priceinclvat": "19.90",
    "volumeml": null,
    "priceperlitre": null,
    "introduced": "2004-12-06",
    "finaldelivery": " ",
    "catgegory": "\u00c3\u2013l, Ale",
    "packaging": "Flaska",
    "captype": "",
    "countryoforigin": "Skottland",
    "countryoforiginlandname": "Storbritannien",
    "producer": "Innis & Gunn",
    "provider": "TOMP Beer Wine & Spirits AB",
    "productionyear": "",
    "testedproductionyear": "",
    "alcoholstrength": "6.6%",
    "module": "",
    "assortment": "FS",
    "organic": "0",
    "kosher": "0"
}, {
    "nr": "1159803",
    "articleid": "506905",
    "articletype": "11598",
    "name": "Innis & Gunn",
    "name2": "Rum Finish Oak Aged Beer",
    "priceinclvat": "19.90",
    "volumeml": null,
    "priceperlitre": null,
    "introduced": "2010-10-01",
    "finaldelivery": " ",
    "catgegory": "\u00c3\u2013l, Ale",
    "packaging": "Flaska",
    "captype": "",
    "countryoforigin": "Skottland",
    "countryoforiginlandname": "Storbritannien",
    "producer": "Innis & Gunn",
    "provider": "TOMP Beer Wine & Spirits AB",
    "productionyear": "",
    "testedproductionyear": "",
    "alcoholstrength": "6.8%",
    "module": "",
    "assortment": "FS",
    "organic": "0",
    "kosher": "0"
}, {
    "nr": "1162001",
    "articleid": "861392",
    "articletype": "11620",
    "name": "MAD",
    "name2": "Salt",
    "priceinclvat": "84.00",
    "volumeml": null,
    "priceperlitre": null,
    "introduced": "2014-09-05",
    "finaldelivery": " ",
    "catgegory": "\u00c3\u2013l, Ale",
    "packaging": "Flaska",
    "captype": "",
    "countryoforigin": "",
    "countryoforiginlandname": "Internationellt m\u00c3\u00a4rke",
    "producer": "MAD Beer",
    "provider": "Brill & Co AB",
    "productionyear": "",
    "testedproductionyear": "",
    "alcoholstrength": "4.5%",
    "module": "",
    "assortment": "TSE",
    "organic": "0",
    "kosher": "0"
},  {
    "nr": "1172601",
    "articleid": "721579",
    "articletype": "11726",
    "name": "La Binchoise",
    "name2": "XO",
    "priceinclvat": "179.00",
    "volumeml": null,
    "priceperlitre": null,
    "introduced": "2013-02-01",
    "finaldelivery": " ",
    "catgegory": "\u00c3\u2013l, Ale",
    "packaging": "Flaska",
    "captype": "",
    "countryoforigin": "",
    "countryoforiginlandname": "Belgien",
    "producer": "La Binchoise",
    "provider": "World Beer Trading KB",
    "productionyear": "",
    "testedproductionyear": "",
    "alcoholstrength": "12%",
    "module": "T7",
    "assortment": "TSE",
    "organic": "0",
    "kosher": "0"
}, {
    "nr": "1177703",
    "articleid": "676236",
    "articletype": "11777",
    "name": "Samichlaus Helles",
    "name2": "",
    "priceinclvat": "35.80",
    "volumeml": null,
    "priceperlitre": null,
    "introduced": "2012-12-01",
    "finaldelivery": " ",
    "catgegory": "\u00c3\u2013l, Ljus lager",
    "packaging": "Flaska",
    "captype": "",
    "countryoforigin": "",
    "countryoforiginlandname": "\u00c3\u2013sterrike",
    "producer": "Brauerei Schloss Eggenberger",
    "provider": "World Beer Trading KB",
    "productionyear": "2012",
    "testedproductionyear": "",
    "alcoholstrength": "14%",
    "module": "T5",
    "assortment": "TSE",
    "organic": "0",
    "kosher": "0"
},  {
    "nr": "128203",
    "articleid": "507169",
    "articletype": "1282",
    "name": "G\u00c3\u00b6sser",
    "name2": "Dark Beer",
    "priceinclvat": "12.10",
    "volumeml": null,
    "priceperlitre": null,
    "introduced": "2010-10-01",
    "finaldelivery": " ",
    "catgegory": "\u00c3\u2013l, M\u00c3\u00b6rk lager",
    "packaging": "Flaska",
    "captype": "",
    "countryoforigin": "",
    "countryoforiginlandname": "\u00c3\u2013sterrike",
    "producer": "Brau Union \u00c3\u2013sterreich",
    "provider": "GL Brands AB",
    "productionyear": "",
    "testedproductionyear": "",
    "alcoholstrength": "4.5%",
    "module": "T9",
    "assortment": "FS",
    "organic": "0",
    "kosher": "0"
},  {
    "nr": "129312",
    "articleid": "510197",
    "articletype": "1293",
    "name": "Henninger",
    "name2": "Premium Bier",
    "priceinclvat": "6.90",
    "volumeml": null,
    "priceperlitre": null,
    "introduced": "2010-10-01",
    "finaldelivery": " ",
    "catgegory": "\u00c3\u2013l, Ljus lager",
    "packaging": "Burk",
    "captype": "",
    "countryoforigin": "",
    "countryoforiginlandname": "Tyskland",
    "producer": "Henninger-Br\u00c3\u00a4u",
    "provider": "TOMP Beer Wine & Spirits AB",
    "productionyear": "",
    "testedproductionyear": "",
    "alcoholstrength": "4.8%",
    "module": "T9",
    "assortment": "FS",
    "organic": "0",
    "kosher": "0"
}, {
    "nr": "150603",
    "articleid": "15107",
    "articletype": "1506",
    "name": "Jever Pilsener",
    "name2": "",
    "priceinclvat": "12.90",
    "volumeml": null,
    "priceperlitre": null,
    "introduced": "1998-03-01",
    "finaldelivery": " ",
    "catgegory": "\u00c3\u2013l, Ljus lager",
    "packaging": "Flaska",
    "captype": "",
    "countryoforigin": "",
    "countryoforiginlandname": "Tyskland",
    "producer": "Friesisches Brauhaus",
    "provider": "TOMP Beer Wine & Spirits AB",
    "productionyear": "",
    "testedproductionyear": "",
    "alcoholstrength": "4.9%",
    "module": "",
    "assortment": "FS",
    "organic": "0",
    "kosher": "0"
}, {
    "nr": "154301",
    "articleid": "626884",
    "articletype": "1543",
    "name": "Lancaster Bomber",
    "name2": "Thwaites",
    "priceinclvat": "22.50",
    "volumeml": null,
    "priceperlitre": null,
    "introduced": "2012-04-02",
    "finaldelivery": " ",
    "catgegory": "\u00c3\u2013l, Ale",
    "packaging": "Flaska",
    "captype": "",
    "countryoforigin": "England",
    "countryoforiginlandname": "Storbritannien",
    "producer": "Daniel Thwaites Brewery",
    "provider": "TOMP Beer Wine & Spirits AB",
    "productionyear": "",
    "testedproductionyear": "",
    "alcoholstrength": "4.4%",
    "module": "",
    "assortment": "FS",
    "organic": "0",
    "kosher": "0"
        }
    ]
};